config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/eosc-user-dashboard:
      branch: master
      repo: https://github.com/cyfronet-fid/eosc-user-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_curious_chinchilla.sh
        container: qc.acc_peach_melancholy_elephant
  QC.Doc:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beige_helpful_starfish.sh
        container: qc.doc_eggplant_mature_impala
      github.com/cyfronet-fid/eosc-user-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.dusk_compassionate_cougar.sh
        container: qc.doc_celadon_helpful_macaw
      github.com/cyfronet-fid/eosc-user-dashboard markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.copper_confident_hedgehog.sh
        container: qc.doc_moss_bright_hummingbird
  QC.Lic:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ash_carefree_dhole.sh
        container: qc.lic_yellow_whimsical_seal
  QC.Sec:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard bandit:
        commands:
        - /usr/bin/env sh .sqa/script.purple_rational_wombat.sh
        container: qc.sec_cyan_grumpy_sparrow
  QC.Sty:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_happy_tortoise.sh
        container: qc.sty_dahlia_productive_lynx
      github.com/cyfronet-fid/eosc-user-dashboard hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_apprehensive_moth.sh
        container: qc.sty_umber_timid_chinchilla
      github.com/cyfronet-fid/eosc-user-dashboard jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_nurturing_heron.sh
        container: qc.sty_chocolate_observant_skunk
  QC.Uni:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cosmos_independent_mink.sh
        container: qc.uni_sage_meticulous_porcupine
  QC.Ver:
    repos:
      github.com/cyfronet-fid/eosc-user-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ceru_tactful_raccoon.sh
        container: qc.ver_obsidian_creative_sloth
timeout: 5400
